/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package co.tagtalk.winemate.thriftfiles;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2017-04-02")
public class AllBottlesResponse implements org.apache.thrift.TBase<AllBottlesResponse, AllBottlesResponse._Fields>, java.io.Serializable, Cloneable, Comparable<AllBottlesResponse> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("AllBottlesResponse");

  private static final org.apache.thrift.protocol.TField ALL_BOTTLES_FIELD_DESC = new org.apache.thrift.protocol.TField("allBottles", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new AllBottlesResponseStandardSchemeFactory());
    schemes.put(TupleScheme.class, new AllBottlesResponseTupleSchemeFactory());
  }

  public List<BottleInfo> allBottles; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ALL_BOTTLES((short)1, "allBottles");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ALL_BOTTLES
          return ALL_BOTTLES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ALL_BOTTLES, new org.apache.thrift.meta_data.FieldMetaData("allBottles", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, BottleInfo.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(AllBottlesResponse.class, metaDataMap);
  }

  public AllBottlesResponse() {
  }

  public AllBottlesResponse(
    List<BottleInfo> allBottles)
  {
    this();
    this.allBottles = allBottles;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public AllBottlesResponse(AllBottlesResponse other) {
    if (other.isSetAllBottles()) {
      List<BottleInfo> __this__allBottles = new ArrayList<BottleInfo>(other.allBottles.size());
      for (BottleInfo other_element : other.allBottles) {
        __this__allBottles.add(new BottleInfo(other_element));
      }
      this.allBottles = __this__allBottles;
    }
  }

  public AllBottlesResponse deepCopy() {
    return new AllBottlesResponse(this);
  }

  @Override
  public void clear() {
    this.allBottles = null;
  }

  public int getAllBottlesSize() {
    return (this.allBottles == null) ? 0 : this.allBottles.size();
  }

  public java.util.Iterator<BottleInfo> getAllBottlesIterator() {
    return (this.allBottles == null) ? null : this.allBottles.iterator();
  }

  public void addToAllBottles(BottleInfo elem) {
    if (this.allBottles == null) {
      this.allBottles = new ArrayList<BottleInfo>();
    }
    this.allBottles.add(elem);
  }

  public List<BottleInfo> getAllBottles() {
    return this.allBottles;
  }

  public AllBottlesResponse setAllBottles(List<BottleInfo> allBottles) {
    this.allBottles = allBottles;
    return this;
  }

  public void unsetAllBottles() {
    this.allBottles = null;
  }

  /** Returns true if field allBottles is set (has been assigned a value) and false otherwise */
  public boolean isSetAllBottles() {
    return this.allBottles != null;
  }

  public void setAllBottlesIsSet(boolean value) {
    if (!value) {
      this.allBottles = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ALL_BOTTLES:
      if (value == null) {
        unsetAllBottles();
      } else {
        setAllBottles((List<BottleInfo>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ALL_BOTTLES:
      return getAllBottles();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ALL_BOTTLES:
      return isSetAllBottles();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof AllBottlesResponse)
      return this.equals((AllBottlesResponse)that);
    return false;
  }

  public boolean equals(AllBottlesResponse that) {
    if (that == null)
      return false;

    boolean this_present_allBottles = true && this.isSetAllBottles();
    boolean that_present_allBottles = true && that.isSetAllBottles();
    if (this_present_allBottles || that_present_allBottles) {
      if (!(this_present_allBottles && that_present_allBottles))
        return false;
      if (!this.allBottles.equals(that.allBottles))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_allBottles = true && (isSetAllBottles());
    list.add(present_allBottles);
    if (present_allBottles)
      list.add(allBottles);

    return list.hashCode();
  }

  @Override
  public int compareTo(AllBottlesResponse other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetAllBottles()).compareTo(other.isSetAllBottles());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAllBottles()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.allBottles, other.allBottles);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("AllBottlesResponse(");
    boolean first = true;

    sb.append("allBottles:");
    if (this.allBottles == null) {
      sb.append("null");
    } else {
      sb.append(this.allBottles);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class AllBottlesResponseStandardSchemeFactory implements SchemeFactory {
    public AllBottlesResponseStandardScheme getScheme() {
      return new AllBottlesResponseStandardScheme();
    }
  }

  private static class AllBottlesResponseStandardScheme extends StandardScheme<AllBottlesResponse> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, AllBottlesResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ALL_BOTTLES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list40 = iprot.readListBegin();
                struct.allBottles = new ArrayList<BottleInfo>(_list40.size);
                BottleInfo _elem41;
                for (int _i42 = 0; _i42 < _list40.size; ++_i42)
                {
                  _elem41 = new BottleInfo();
                  _elem41.read(iprot);
                  struct.allBottles.add(_elem41);
                }
                iprot.readListEnd();
              }
              struct.setAllBottlesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, AllBottlesResponse struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.allBottles != null) {
        oprot.writeFieldBegin(ALL_BOTTLES_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.allBottles.size()));
          for (BottleInfo _iter43 : struct.allBottles)
          {
            _iter43.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class AllBottlesResponseTupleSchemeFactory implements SchemeFactory {
    public AllBottlesResponseTupleScheme getScheme() {
      return new AllBottlesResponseTupleScheme();
    }
  }

  private static class AllBottlesResponseTupleScheme extends TupleScheme<AllBottlesResponse> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, AllBottlesResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetAllBottles()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetAllBottles()) {
        {
          oprot.writeI32(struct.allBottles.size());
          for (BottleInfo _iter44 : struct.allBottles)
          {
            _iter44.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, AllBottlesResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list45 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.allBottles = new ArrayList<BottleInfo>(_list45.size);
          BottleInfo _elem46;
          for (int _i47 = 0; _i47 < _list45.size; ++_i47)
          {
            _elem46 = new BottleInfo();
            _elem46.read(iprot);
            struct.allBottles.add(_elem46);
          }
        }
        struct.setAllBottlesIsSet(true);
      }
    }
  }

}

